services:
  api:
    container_name: api-download
    image: api-download
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: 1000M